import HomeIcon from '@sanity/icons/Home'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Home page',
  type: 'document',
  icon: HomeIcon,
  groups: [
    {name: 'hero', title: 'Hero'},
    {name: 'services', title: 'Services'},
    {name: 'atendimento', title: 'Atendimento'},
    {name: 'content', title: 'Other content'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'pageHero',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'decorativeSignature', type: 'cmsImage', group: 'hero'}),
    defineField({
      name: 'introductionEyebrow',
      title: 'Introduction eyebrow',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'introductionTitle',
      title: 'Introduction title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'introductionText',
      title: 'Introduction text',
      type: 'text',
      rows: 5,
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'servicesEyebrow',
      title: 'Services eyebrow',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesTitle',
      title: 'Services title',
      type: 'string',
      group: 'services',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'servicesDescription',
      title: 'Services description',
      type: 'text',
      rows: 3,
      group: 'services',
    }),
    defineField({
      name: 'servicesCta',
      title: 'Services call to action',
      type: 'callToAction',
      group: 'services',
    }),
    defineField({
      name: 'featuredServices',
      title: 'Featured services',
      type: 'array',
      group: 'services',
      of: [defineArrayMember({type: 'reference', to: [{type: 'service'}]})],
    }),
    defineField({
      name: 'timelineEyebrow',
      title: 'Timeline eyebrow',
      type: 'string',
      group: 'atendimento',
    }),
    defineField({
      name: 'timelineTitle',
      title: 'Timeline title',
      type: 'string',
      group: 'atendimento',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'timelineDescription',
      title: 'Timeline description',
      type: 'text',
      rows: 3,
      group: 'atendimento',
    }),
    defineField({
      name: 'timeline',
      title: 'Atendimento steps',
      type: 'array',
      group: 'atendimento',
      of: [defineArrayMember({type: 'timelineStep'})],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: 'valuesTitle',
      title: 'Values title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'values',
      title: 'Values',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'valueItem'})],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: 'faqTitle',
      title: 'FAQ title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'faqDescription',
      title: 'FAQ description',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'faqCta',
      title: 'FAQ call to action',
      type: 'callToAction',
      group: 'content',
    }),
    defineField({
      name: 'faqs',
      title: 'Home FAQs',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'faqItem'})],
    }),
    defineField({
      name: 'articlesTitle',
      title: 'Articles title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'articlesDescription',
      title: 'Articles description',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'articlesCta',
      title: 'Articles call to action',
      type: 'callToAction',
      group: 'content',
    }),
    defineField({
      name: 'closingCta',
      title: 'Closing call to action',
      type: 'pageHero',
      group: 'content',
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
})
